### ISSUE TITLE
[Proposal] Delete this repository - One-Multi-Week Coding exercises should be banned

### ISSUE THREAD

**Issue by exapsy** [arvanitisgeorge/node_exercise#1]
## Proposal

Coding exercises like this one send entirely the wrong message about how to respect somebody's time.

Imagine this scenario:
> You're clearly searching for a job.
> A company comes and tells you "You have 1 week to finish this task". 
> Important, You don't even know if that company is going to hire you, whether you do the task or not.
> 
> Now you have an interview with another company. 
> That company comes and tells you "you have 2 weeks to do this task"

Now you are basically working for free for 2 separate companies that you don't even know whether they're going to hire you or not, asking you to make 2 separate exercises. Doesn't that feel... completely company-centric and completely disrespectful to the candidate's time let alone their mental health?

Now you have another interview, and they tell you "hey we like you, we want a 2nd, 3rd, 4th interview even" (I've reached even several 7 stage interviews), so now you occupy time from your 1-2 weeks tasks for these interviews.
There is even a Youtube documentary about it from Economics Explained: [Why Are Companies Making You Do So Many Job Interviews Now?](https://www.youtube.com/watch?v=5KjNlPi9CUM), but that's about the multi-stage interviews. Another type of cancer in the industry, which also collides with week tasks from other companies.

When it's asked from a candidate to occupy 1 week of their time just for your company that doesn't even know if they're going to hire them or not, you're basically asking them to gamble 168 hours of their time - sleep time - free time if your exercise allows it, just so they make the exercise of that said company.

When you have a surgeon interview you don't tell the surgeon "hey, let's put you for 1-2 weeks in a surgery VR simulation".
Or when you have a lawyer, you don't make pseudo-courts with pseudo-cases to test his knowledge.
Both are ridiculous. How is it not in our software engineering/developing industry?

There are so many much better ways to find out if an employee knows how to make an app and how to architecture it. 
**Github even**! 
You can look at my own Github! 

Why put me under the stress of making the company's own exercise when you can just take a look at which companies I've worked for, at my github, what did I do etc? It's ridiculous.

Let's put a stop at this movement of "have a 1 week task" "2 week task". 

We have a life.
We have other interviews with other companies.
I don't even know if the company is going to hire me even if my exercise was made with much effort, which I gambled so much of my own personal time of.
It is clearly exhausting and makes puts every candidate under a week of mental stress just for one company as if it's the ultimate court. 

Company doesn't like me? They can just fire me and find another applicant. It's that easy. And also put better questions or  small enough tasks to fit an interview to get a deeper knowledge of what the candidate is better at.
 
But that whole "make 1-2 week task" or "have 7 stage interview" is just ridiculous, rob's the candidate's free time, and I'm tired of pretending it is not ridiculous and is not disrespectful to the candidates' time.

What I'm proposing, is to straight up delete the repository and not give any more encouragement to the industry to exploit people's time like that without offering them anything. The arguments of why are straight above.

**Comment by arvanitisgeorge** [comment]
Dear candidate,

Unfortunately, I am not still part of PCCW Global. I am a former employee. However, I am one of the authors of this exercise. 
So, read the rest of my answer keeping in mind that I do NOT represent the company. 

I really understand your frustration. I understand that you need time in order to finish this exercise and you also do not know if this is gonna be a successful result for you. I have been in your shoes many times in the past. I felt the same. However, you should keep in mind that:
- as soon as you have the right to choose which company you want to work for, the company has the right to have an interview process that prefers. Then, every candidate, has the free will to choose, if he is going to finish this exercise, do it partially, or even do not do it at all. Think of it as a 100m sprinter, that now has to show that he is fast enough in 200m run too. Someone (in our case a company) will start to invest money on a sprinter. He will mainly run 200m if he got hired. The company has the right to get more chances that the investment is gonna be successful. Will you spend your money on an uncertain investment?
- I will suggest you not avoiding interview exercises (as soon as they do not add stress on you), because this is a good way to get out of your comfort zone and teach you many new things that you did not know that were existing. 
- An interviewer can see many things in a candidate's GitHub profile. However, he might want to see a candidates approach to a specific problem, that is a small image of an a-day-at-work. 
- Apart form the tech skills, soft skills is part of our work too. Frustration might happen, but should never "navigate" our manners. 
- A company might not want to hire someone and then decide if he is suitable or not. This is unprofessional for the hired person too. Imagine that you have started working for a company. Then, you rented after a month a house with your girlfriend and after a second month, the company chose to fire you. Think of a case that you have children. Things might be even worst. 

It is totally fine to avoid doing an exercise. By not doing an exercise, it does not mean that you are not good enough, or that you might not be a good candidate in the future for any company. 
I hope that you find my comment useful. Also, I really hope you find the best company that suit your needs. 

Best regards.
